<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    public function run()
    {
        $users = [
            // SUPER ADMIN
            [
                'name' => 'Super Admin',
                'email' => 'admin@beautystore.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'first_name' => 'Super',
                'last_name' => 'Admin',
                'phone' => '+33123456789',
                'birth_date' => '1985-03-15',
                'gender' => 'other',
                'address_line_1' => '123 Rue de la Beauté',
                'address_line_2' => 'Bâtiment A',
                'city' => 'Paris',
                'postal_code' => '75001',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'notifications' => ['email', 'sms'],
                    'marketing' => true
                ]),
                'newsletter_subscribed' => true,
                'last_login_at' => now()->subHours(2),
                'last_login_ip' => '192.168.1.100',
                'role' => 'super_admin',
                'is_active' => true,
                'total_spent' => 0.00,
                'orders_count' => 0,
            ],

            // ADMIN
            [
                'name' => 'Marie Dubois',
                'email' => 'marie.dubois@beautystore.com',
                'email_verified_at' => now(),
                'password' => Hash::make('admin2024'),
                'remember_token' => Str::random(10),
                'first_name' => 'Marie',
                'last_name' => 'Dubois',
                'phone' => '+33156789012',
                'birth_date' => '1990-07-22',
                'gender' => 'female',
                'address_line_1' => '45 Avenue des Champs-Élysées',
                'address_line_2' => null,
                'city' => 'Paris',
                'postal_code' => '75008',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'notifications' => ['email'],
                    'admin_dashboard' => 'advanced'
                ]),
                'newsletter_subscribed' => false,
                'last_login_at' => now()->subMinutes(30),
                'last_login_ip' => '192.168.1.101',
                'role' => 'admin',
                'is_active' => true,
                'total_spent' => 245.80,
                'orders_count' => 2,
            ],

            // CLIENTS VIP
            [
                'name' => 'Sophie Laurent',
                'email' => 'sophie.laurent@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('sophie2024'),
                'remember_token' => Str::random(10),
                'first_name' => 'Sophie',
                'last_name' => 'Laurent',
                'phone' => '+33612345678',
                'birth_date' => '1988-12-03',
                'gender' => 'female',
                'address_line_1' => '12 Rue de Rivoli',
                'address_line_2' => 'Appartement 5B',
                'city' => 'Paris',
                'postal_code' => '75001',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'favorite_brands' => ['Chanel', 'Dior', 'YSL'],
                    'favorite_categories' => ['Parfums', 'Cosmétiques'],
                    'notifications' => ['email', 'sms'],
                    'vip_member' => true
                ]),
                'newsletter_subscribed' => true,
                'last_login_at' => now()->subDays(1),
                'last_login_ip' => '82.234.567.123',
                'role' => 'customer',
                'is_active' => true,
                'total_spent' => 1247.50,
                'orders_count' => 12,
            ],
            [
                'name' => 'Camille Moreau',
                'email' => 'camille.moreau@outlook.fr',
                'email_verified_at' => now(),
                'password' => Hash::make('camille123'),
                'remember_token' => Str::random(10),
                'first_name' => 'Camille',
                'last_name' => 'Moreau',
                'phone' => '+33698765432',
                'birth_date' => '1992-05-18',
                'gender' => 'female',
                'address_line_1' => '78 Boulevard Saint-Germain',
                'address_line_2' => null,
                'city' => 'Paris',
                'postal_code' => '75006',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'favorite_brands' => ['MAC', 'NARS', 'Byredo'],
                    'skin_tone' => 'medium',
                    'notifications' => ['email']
                ]),
                'newsletter_subscribed' => true,
                'last_login_at' => now()->subHours(6),
                'last_login_ip' => '90.123.456.789',
                'role' => 'customer',
                'is_active' => true,
                'total_spent' => 892.30,
                'orders_count' => 8,
            ],

            // CLIENTS RÉGULIERS
            [
                'name' => 'Julien Martin',
                'email' => 'julien.martin@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('julien2024'),
                'remember_token' => Str::random(10),
                'first_name' => 'Julien',
                'last_name' => 'Martin',
                'phone' => '+33634567890',
                'birth_date' => '1987-09-14',
                'gender' => 'male',
                'address_line_1' => '25 Rue de la Paix',
                'address_line_2' => null,
                'city' => 'Lyon',
                'postal_code' => '69001',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'favorite_brands' => ['Dior', 'Tom Ford', 'Hugo Boss'],
                    'notifications' => ['email']
                ]),
                'newsletter_subscribed' => false,
                'last_login_at' => now()->subDays(3),
                'last_login_ip' => '78.234.567.890',
                'role' => 'customer',
                'is_active' => true,
                'total_spent' => 456.70,
                'orders_count' => 4,
            ],
            [
                'name' => 'Emma Petit',
                'email' => 'emma.petit@yahoo.fr',
                'email_verified_at' => now(),
                'password' => Hash::make('emma2024'),
                'remember_token' => Str::random(10),
                'first_name' => 'Emma',
                'last_name' => 'Petit',
                'phone' => '+33645678901',
                'birth_date' => '1995-02-28',
                'gender' => 'female',
                'address_line_1' => '156 Avenue Victor Hugo',
                'address_line_2' => 'Résidence Les Jardins',
                'city' => 'Nice',
                'postal_code' => '06000',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'favorite_categories' => ['Soins', 'Cosmétiques'],
                    'skin_type' => 'sensitive',
                    'notifications' => ['email', 'push']
                ]),
                'newsletter_subscribed' => true,
                'last_login_at' => now()->subDays(2),
                'last_login_ip' => '91.123.789.456',
                'role' => 'customer',
                'is_active' => true,
                'total_spent' => 234.90,
                'orders_count' => 3,
            ],

            // NOUVEAUX CLIENTS
            [
                'name' => 'Lucas Bonnet',
                'email' => 'lucas.bonnet@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('lucas123'),
                'remember_token' => Str::random(10),
                'first_name' => 'Lucas',
                'last_name' => 'Bonnet',
                'phone' => '+33656789012',
                'birth_date' => '1994-11-07',
                'gender' => 'male',
                'address_line_1' => '89 Rue du Faubourg Saint-Honoré',
                'address_line_2' => null,
                'city' => 'Paris',
                'postal_code' => '75008',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'notifications' => ['email']
                ]),
                'newsletter_subscribed' => true,
                'last_login_at' => now()->subHours(4),
                'last_login_ip' => '85.234.567.123',
                'role' => 'customer',
                'is_active' => true,
                'total_spent' => 89.00,
                'orders_count' => 1,
            ],
            [
                'name' => 'Léa Rousseau',
                'email' => 'lea.rousseau@hotmail.fr',
                'email_verified_at' => now(),
                'password' => Hash::make('lea2024'),
                'remember_token' => Str::random(10),
                'first_name' => 'Léa',
                'last_name' => 'Rousseau',
                'phone' => '+33667890123',
                'birth_date' => '1998-04-12',
                'gender' => 'female',
                'address_line_1' => '34 Place Bellecour',
                'address_line_2' => null,
                'city' => 'Lyon',
                'postal_code' => '69002',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'student_discount' => true,
                    'notifications' => ['email', 'push']
                ]),
                'newsletter_subscribed' => true,
                'last_login_at' => now()->subHours(12),
                'last_login_ip' => '92.345.678.901',
                'role' => 'customer',
                'is_active' => true,
                'total_spent' => 0.00,
                'orders_count' => 0,
            ],
            [
                'name' => 'Thomas Girard',
                'email' => 'thomas.girard@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('thomas123'),
                'remember_token' => Str::random(10),
                'first_name' => 'Thomas',
                'last_name' => 'Girard',
                'phone' => '+33678901234',
                'birth_date' => '1991-08-25',
                'gender' => 'male',
                'address_line_1' => '67 Cours Mirabeau',
                'address_line_2' => null,
                'city' => 'Aix-en-Provence',
                'postal_code' => '13100',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'notifications' => ['email']
                ]),
                'newsletter_subscribed' => false,
                'last_login_at' => now()->subDays(5),
                'last_login_ip' => '87.123.456.789',
                'role' => 'customer',
                'is_active' => true,
                'total_spent' => 165.00,
                'orders_count' => 1,
            ],

            // CLIENT INACTIF
            [
                'name' => 'Pierre Durand',
                'email' => 'pierre.durand@wanadoo.fr',
                'email_verified_at' => now()->subMonths(6),
                'password' => Hash::make('pierre123'),
                'remember_token' => Str::random(10),
                'first_name' => 'Pierre',
                'last_name' => 'Durand',
                'phone' => '+33689012345',
                'birth_date' => '1975-06-30',
                'gender' => 'male',
                'address_line_1' => '123 Avenue de la République',
                'address_line_2' => null,
                'city' => 'Marseille',
                'postal_code' => '13001',
                'country' => 'France',
                'preferences' => json_encode([
                    'language' => 'fr',
                    'currency' => 'EUR',
                    'notifications' => ['email']
                ]),
                'newsletter_subscribed' => false,
                'last_login_at' => now()->subMonths(3),
                'last_login_ip' => '86.234.567.890',
                'role' => 'customer',
                'is_active' => false,
                'total_spent' => 678.90,
                'orders_count' => 5,
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert(array_merge($user, [
                'created_at' => now()->subDays(rand(1, 365)),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✅ Users seedés avec succès!');
        $this->command->info('👥 Créés: 1 Super Admin, 1 Admin, 8 Clients (dont 2 VIP, 4 réguliers, 3 nouveaux, 1 inactif)');
    }
}